- hosts: masternode,localhost
  become: yes
  tasks:
    - name: disable swap
      command: "{{ item.cmd }}"
      become: yes
      loop:
        - {cmd: "swapoff -a"}
      tags: swap

    - name: update /etc/hosts file for nodes
      blockinfile:
        path: /etc/hosts
        block: |
          192.168.50.4 masternode
          192.168.50.9 workernode
      become: yes

    - name: stop firewalld
      service:
        name: firewalld
        state: stopped
      become: yes

    - name: Download k3s install script
      get_url: 
        url: https://get.k3s.io
        dest: /vagrant/install.sh

    - name: running install.sh with defined environments
      command: sh /vagrant/install.sh
      environment:
        K3S_KUBECONFIG_MODE: "644"
        K3S_TOKEN: rocky
        INSTALL_K3S_EXEC: "--node-external-ip 192.168.50.4 --node-ip 192.168.50.4"
      register: k3s_server_install
