- hosts: docker
  tasks:
    - name: "docker is present or not"
      command: rpm -qa docker-ce
      register: check

    - name: "downloading docker-ce version 18"
      yum:
        name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-18.06.0.ce-3.el7.x86_64.rpm
        disable_gpg_check: yes
        state: present
      tags:
        - install_docker
      when: check.stdout != "docker-ce-18.06.0.ce-3.el7.x86_64"
      register: docker
      become: yes
    
    - debug:
        msg: "Docker is already installed"
      when: docker['changed'] == false

    - debug:
        msg: "Docker-ce successfully installed"
      when: docker['changed'] == true
    
    - name: "starting service"
      service:
        name: docker
        state: started
      tags:
        - start_docker
      become: yes
    - name: downloading pip module for python2
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /vagrant/

    - name: installing pip module
      command: python /vagrant/get-pip.py
      become: yes
