FROM ubuntu:18.04

WORKDIR /webapp
RUN apt-get update
RUN apt install python3 python3-pip libpq-dev python3-dev -y
RUN apt-get update
#RUN pip3 install virtualenv
#RUN virtualenv env
#RUN source env/bin/activate
RUN pip3 install fastapi  python-multipart jinja2 psycopg2
RUN pip3 install uvicorn
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
VOLUME . /webapp
CMD ["uvicorn","main:app", "--host","$(hostname -I)", "--reload"]