FROM python:3.9 
WORKDIR /code
RUN pip3 install fastapi  python-multipart jinja2 psycopg2
RUN pip3 install uvicorn
COPY main.py .
COPY templates .
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]