apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec: #this spec meant for deployment
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template: #template equals to nginx_pod.yml that inlining ngnix_pod.yml
    metadata:
      name: nginx_pod
      labels:
        app: nginx
        environment: 'production'
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: cm9vdAo=
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: d2ViQXBwREIK
        - name: DB_URL
          value: mongo-service
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx #should be shame as pod's metadata's label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 #should be same as containerport
      nodePort: 30124 #nginx homepage will available on workernodeIP:30124