Vagrant.configure("2") do |config|
  config.vm.define "workernode" do |subconfig|
    subconfig.vm.box = "centos/7"
    subconfig.vm.hostname = "workernode"
    subconfig.vm.network "private_network", ip: "192.168.50.9"
    subconfig.vm.network "public_network", bridge: "BRIDGE"
  end
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "/vagrant/ansible_playbook/playbook.yml"
  end
end
