Vagrant.configure("2") do |config|
  config.vm.define "workernode" do |subconfig|
    subconfig.vm.box = "generic/centos8"
    subconfig.vm.box_version = "4.3.12"
    subconfig.vm.hostname = "workernode"
    subconfig.vm.network "private_network", ip: "192.168.56.51"
    #subconfig.vm.network "public_network", bridge: "BRIDGE"
  end
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1524"
  end
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "/vagrant/ansible_playbook/playbook.yml"
  end
end
