Vagrant.configure("2") do |config|
  config.vm.define "masternode" do |subconfig|
    subconfig.vm.box = "generic/centos8"
    subconfig.vm.box_version = "4.3.12" 
    subconfig.vm.hostname = "masternode"
    subconfig.vm.network "private_network", ip: "192.168.56.50"
    #subconfig.vm.network "public_network", bridge: "BRIDGE"
  end
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1524"
  end
  $script = <<-SCRIPT
sudo setenforce 0
sudo systemctl stop firewalld
curl -sfL https://get.k3s.io | INSTALL_K3S_SELINUX_WARN=true INSTALL_K3S_SKIP_SELINUX_RPM=true K3S_KUBECONFIG_MODE=644 K3S_TOKEN=YOUR_TOKEN_VALUE sh -  
SCRIPT
  config.vm.provision "shell", inline: $script
end
